# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi

pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
- name: "EmbeddingIntentClassifier"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: FallbackPolicy
    fallback_action_name: "action_default_fallback"
  - name: MemoizationPolicy
  - name: FormPolicy
  - name: MappingPolicy
  - name: KerasPolicy
    state_featurizer:
      - name: FullDialogueTrackerFeaturizer
    attn_shift_range: 2
    embed_dim: 20
    epochs: 400
    rnn size: 32
    hidden_layers_sizes_a: []
    hidden_layers_sizes_b: []
